// ===========================================================================
// 此文件由工具自动生成，请勿直接编辑！
// This file is auto-generated by a tool, please do not edit it directly!
// ===========================================================================

using Newtonsoft.Json;
using UnityEngine;

namespace Game
{
    /// <summary>
    /// Item 数据表
    /// </summary>
    public class ItemDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
        /// <summary>
        /// 图标
        /// </summary>
        [JsonProperty]
        public string icon { get; private set; }
    }

    /// <summary>
    /// ARecipe 数据表
    /// </summary>
    public class ARecipeDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
        /// <summary>
        /// 输入物品
        /// </summary>
        [JsonProperty]
        public int[] input_item { get; private set; }
        /// <summary>
        /// 输入数量
        /// </summary>
        [JsonProperty]
        public int[] input_count { get; private set; }
        /// <summary>
        /// 输入接口
        /// </summary>
        [JsonProperty]
        public int[] input_interface { get; private set; }
        /// <summary>
        /// 输出物品
        /// </summary>
        [JsonProperty]
        public int[] output_item { get; private set; }
        /// <summary>
        /// 输出数量
        /// </summary>
        [JsonProperty]
        public int[] output_count { get; private set; }
        /// <summary>
        /// 输出接口
        /// </summary>
        [JsonProperty]
        public int[] output_interface { get; private set; }
        /// <summary>
        /// 生产条件
        /// </summary>
        [JsonProperty]
        public string condition { get; private set; }
    }

    /// <summary>
    /// BRecipe 数据表
    /// </summary>
    public class BRecipeDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
    }

    /// <summary>
    /// GameMode 数据表
    /// </summary>
    public class GameModeDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
    }

    /// <summary>
    /// Planet 数据表
    /// </summary>
    public class PlanetDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
    }

    /// <summary>
    /// Interface 数据表
    /// </summary>
    public class InterfaceDataRow
    {
        /// <summary>
        /// ID
        /// </summary>
        [JsonProperty]
        public int id { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        [JsonProperty]
        public string name { get; private set; }
    }

    public static class SheetDatabase
    {
        public static ItemDataRow[] ItemData { get; private set; }
        public static ARecipeDataRow[] ARecipeData { get; private set; }
        public static BRecipeDataRow[] BRecipeData { get; private set; }
        public static GameModeDataRow[] GameModeData { get; private set; }
        public static PlanetDataRow[] PlanetData { get; private set; }
        public static InterfaceDataRow[] InterfaceData { get; private set; }

        public static void LoadData()
        {
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/Item");
                if (jsonFile != null)
                {
                    ItemData = JsonConvert.DeserializeObject<ItemDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/Item");
                }
            }
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/ARecipe");
                if (jsonFile != null)
                {
                    ARecipeData = JsonConvert.DeserializeObject<ARecipeDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/ARecipe");
                }
            }
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/BRecipe");
                if (jsonFile != null)
                {
                    BRecipeData = JsonConvert.DeserializeObject<BRecipeDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/BRecipe");
                }
            }
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/GameMode");
                if (jsonFile != null)
                {
                    GameModeData = JsonConvert.DeserializeObject<GameModeDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/GameMode");
                }
            }
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/Planet");
                if (jsonFile != null)
                {
                    PlanetData = JsonConvert.DeserializeObject<PlanetDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/Planet");
                }
            }
            {
                TextAsset jsonFile = Resources.Load<TextAsset>("SheetDatabase/JSON/Interface");
                if (jsonFile != null)
                {
                    InterfaceData = JsonConvert.DeserializeObject<InterfaceDataRow[]>(jsonFile.text);
                }
                else
                {
                    Debug.LogError("Cannot find sheet data SheetDatabase/JSON/Interface");
                }
            }
        }
    }
}